### ISSUE TITLE
UI support for RMQ 

### ISSUE THREAD

**Issue by SaiAravindVemuri** [springwolf/springwolf-rabbitmq#2]
Hi,

I can able to generate RMQ specs in the JSON format. I want an UI plugin which renders the JSON and displays it in Async-API UI.

Thanks in advance

**Comment by stavshamir** [comment]
Hi @SaiAravindVemuri, I recently created [springwolf-app](https://github.com/springwolf/springwolf-app) which I think exactly answers your needs. 
Please check it out and let me know what you think. If there are missing features or bugs, I'll be happy to address them.
